name: Deploy to ECS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy to ECS
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3

      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

     
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

     
      - name: Build, tag, and push Docker image
        run: |
          IMAGE_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app:latest
          docker build -t wild-rydes-app .
          docker tag wild-rydes-app:latest $IMAGE_URI
          docker push $IMAGE_URI

     
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          service: wild-rydes-service
          cluster: wild-rydes-cluster
          wait-for-service-stability: true

      
      - name: Notify developers of deployment
        run: |
          aws sns publish \
            --topic-arn arn:aws:sns:us-east-1:${{ secrets.AWS_ACCOUNT_ID }}:ecs-deploy-alerts \
            --subject "Wild Rydes Deployment Complete" \
            --message "A new version of Wild Rydes was successfully deployed to ECS."
